### ISSUE TITLE
linux运行的时候报了空指针，windows运行正常

### ISSUE THREAD

**Issue by guohuiyuan** [wuchunfu/IpProxyPool#56]
![image](https://user-images.githubusercontent.com/54976075/141778396-85203e68-6cfa-42a5-9b54-7f2bcbd10b3c.png)

**Comment by wuchunfu** [comment]
可以详细说一下具体情况么？
可能是因为网络不稳定，导致没有成功抓取代理，你可以在运行一下试试

**Comment by guohuiyuan** [comment]
> 可以详细说一下具体情况么？ 可能是因为网络不稳定，导致没有成功抓取代理，你可以在运行一下试试

就是改了配置，其他没动，linux报空指针，windows正常
![image](https://user-images.githubusercontent.com/54976075/141941789-1f5587ea-fc30-4af1-81ea-e1734c377ff5.png)

**Comment by guohuiyuan** [comment]
> 可以详细说一下具体情况么？ 可能是因为网络不稳定，导致没有成功抓取代理，你可以在运行一下试试

作者在linux环境试过吗😂

**Comment by wuchunfu** [comment]
我没有在 linux 上测试过，我用的是 mac book，我有时间了在全面测试下
